name: lint

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # golangci-lint
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.57.2
          golangci-lint --version
          # pre-commit
          pip install pre-commit
          pre-commit --version

      - name: Run pre-commit
        run: |
          pre-commit run --all-files
