name: lint

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Install any dependencies required to run pre-commit
          pip install pre-commit

      - name: Run pre-commit
        run: |
          # Run pre-commit on all files
          pre-commit run --all-files
